
/*
 * Copyright (C) 2024-2025  Yomitan Authors
 * Adapted for LinguaFlow
 */

export interface Rule {
    suffixIn: string;
    suffixOut: string;
    conditionsIn: string[];
    conditionsOut: string[];
}

export const suffixInflection = (suffixIn: string, suffixOut: string, conditionsIn: string[], conditionsOut: string[]): Rule => ({
    suffixIn,
    suffixOut,
    conditionsIn,
    conditionsOut
});

const shimauEnglishDescription = '1. Shows a sense of regret/surprise when you did have volition in doing something, but it turned out to be bad to do.\n' +
'2. Shows perfective/punctual achievement. This shows that an action has been completed.\n' +
'3. Shows unintentional action–“accidentally”.\n';

const passiveEnglishDescription = '1. Indicates an action received from an action performer.\n' +
'2. Expresses respect for the subject of action performer.\n';

const ikuVerbs = ['いく', '行く', '逝く', '往く'];
const godanUSpecialVerbs = ['こう', 'とう', '請う', '乞う', '恋う', '問う', '訪う', '宣う', '曰う', '給う', '賜う', '揺蕩う'];
const fuVerbTeConjugations = [
    ['のたまう', 'のたもう'],
    ['たまう', 'たもう'],
    ['たゆたう', 'たゆとう'],
];

function irregularVerbSuffixInflections(suffix: 'て' | 'た' | 'たら' | 'たり', conditionsIn: string[], conditionsOut: string[]) {
    const inflections = [];
    for (const verb of ikuVerbs) {
        inflections.push(suffixInflection(`${verb[0]}っ${suffix}`, verb, conditionsIn, conditionsOut));
    }
    for (const verb of godanUSpecialVerbs) {
        inflections.push(suffixInflection(`${verb}${suffix}`, verb, conditionsIn, conditionsOut));
    }
    for (const [verb, teRoot] of fuVerbTeConjugations) {
        inflections.push(suffixInflection(`${teRoot}${suffix}`, verb, conditionsIn, conditionsOut));
    }
    return inflections;
}

export const japaneseTransforms = {
    language: 'ja',
    transforms: {
        '-ば': {
            name: '-ば',
            rules: [
                suffixInflection('ければ', 'い', ['-ば'], ['adj-i']),
                suffixInflection('えば', 'う', ['-ば'], ['v5']),
                suffixInflection('けば', 'く', ['-ば'], ['v5']),
                suffixInflection('げば', 'ぐ', ['-ば'], ['v5']),
                suffixInflection('せば', 'す', ['-ば'], ['v5']),
                suffixInflection('てば', 'つ', ['-ば'], ['v5']),
                suffixInflection('ねば', 'ぬ', ['-ば'], ['v5']),
                suffixInflection('べば', 'ぶ', ['-ば'], ['v5']),
                suffixInflection('めば', 'む', ['-ば'], ['v5']),
                suffixInflection('れば', 'る', ['-ば'], ['v1', 'v5', 'vk', 'vs', 'vz']),
                suffixInflection('れば', '', ['-ば'], ['-ます']),
            ],
        },
        '-ゃ': {
            name: '-ゃ',
            rules: [
                suffixInflection('けりゃ', 'ければ', ['-ゃ'], ['-ば']),
                suffixInflection('きゃ', 'ければ', ['-ゃ'], ['-ば']),
                suffixInflection('や', 'えば', ['-ゃ'], ['-ば']),
                suffixInflection('きゃ', 'けば', ['-ゃ'], ['-ば']),
                suffixInflection('ぎゃ', 'げば', ['-ゃ'], ['-ば']),
                suffixInflection('しゃ', 'せば', ['-ゃ'], ['-ば']),
                suffixInflection('ちゃ', 'てば', ['-ゃ'], ['-ば']),
                suffixInflection('にゃ', 'ねば', ['-ゃ'], ['-ば']),
                suffixInflection('びゃ', 'べば', ['-ゃ'], ['-ば']),
                suffixInflection('みゃ', 'めば', ['-ゃ'], ['-ば']),
                suffixInflection('りゃ', 'れば', ['-ゃ'], ['-ば']),
            ],
        },
        '-ちゃ': {
            name: '-ちゃ',
            rules: [
                suffixInflection('ちゃ', 'る', ['v5'], ['v1']),
                suffixInflection('いじゃ', 'ぐ', ['v5'], ['v5']),
                suffixInflection('いちゃ', 'く', ['v5'], ['v5']),
                suffixInflection('しちゃ', 'す', ['v5'], ['v5']),
                suffixInflection('っちゃ', 'う', ['v5'], ['v5']),
                suffixInflection('っちゃ', 'く', ['v5'], ['v5']),
                suffixInflection('っちゃ', 'つ', ['v5'], ['v5']),
                suffixInflection('っちゃ', 'る', ['v5'], ['v5']),
                suffixInflection('んじゃ', 'ぬ', ['v5'], ['v5']),
                suffixInflection('んじゃ', 'ぶ', ['v5'], ['v5']),
                suffixInflection('んじゃ', 'む', ['v5'], ['v5']),
                suffixInflection('じちゃ', 'ずる', ['v5'], ['vz']),
                suffixInflection('しちゃ', 'する', ['v5'], ['vs']),
                suffixInflection('為ちゃ', '為る', ['v5'], ['vs']),
                suffixInflection('きちゃ', 'くる', ['v5'], ['vk']),
                suffixInflection('来ちゃ', '来る', ['v5'], ['vk']),
                suffixInflection('來ちゃ', '來る', ['v5'], ['vk']),
            ],
        },
        '-ちゃう': {
            name: '-ちゃう',
            rules: [
                suffixInflection('ちゃう', 'る', ['v5'], ['v1']),
                suffixInflection('いじゃう', 'ぐ', ['v5'], ['v5']),
                suffixInflection('いちゃう', 'く', ['v5'], ['v5']),
                suffixInflection('しちゃう', 'す', ['v5'], ['v5']),
                suffixInflection('っちゃう', 'う', ['v5'], ['v5']),
                suffixInflection('っちゃう', 'く', ['v5'], ['v5']),
                suffixInflection('っちゃう', 'つ', ['v5'], ['v5']),
                suffixInflection('っちゃう', 'る', ['v5'], ['v5']),
                suffixInflection('んじゃう', 'ぬ', ['v5'], ['v5']),
                suffixInflection('んじゃう', 'ぶ', ['v5'], ['v5']),
                suffixInflection('んじゃう', 'む', ['v5'], ['v5']),
                suffixInflection('じちゃう', 'ずる', ['v5'], ['vz']),
                suffixInflection('しちゃう', 'する', ['v5'], ['vs']),
                suffixInflection('為ちゃう', '為る', ['v5'], ['vs']),
                suffixInflection('きちゃう', 'くる', ['v5'], ['vk']),
                suffixInflection('来ちゃう', '来る', ['v5'], ['vk']),
                suffixInflection('來ちゃう', '來る', ['v5'], ['vk']),
            ],
        },
        '-ちまう': {
            name: '-ちまう',
            rules: [
                suffixInflection('ちまう', 'る', ['v5'], ['v1']),
                suffixInflection('いじまう', 'ぐ', ['v5'], ['v5']),
                suffixInflection('いちまう', 'く', ['v5'], ['v5']),
                suffixInflection('しちまう', 'す', ['v5'], ['v5']),
                suffixInflection('っちまう', 'う', ['v5'], ['v5']),
                suffixInflection('っちまう', 'く', ['v5'], ['v5']),
                suffixInflection('っちまう', 'つ', ['v5'], ['v5']),
                suffixInflection('っちまう', 'る', ['v5'], ['v5']),
                suffixInflection('んじまう', 'ぬ', ['v5'], ['v5']),
                suffixInflection('んじまう', 'ぶ', ['v5'], ['v5']),
                suffixInflection('んじまう', 'む', ['v5'], ['v5']),
                suffixInflection('じちまう', 'ずる', ['v5'], ['vz']),
                suffixInflection('しちまう', 'する', ['v5'], ['vs']),
                suffixInflection('為ちまう', '為る', ['v5'], ['vs']),
                suffixInflection('きちまう', 'くる', ['v5'], ['vk']),
                suffixInflection('来ちまう', '来る', ['v5'], ['vk']),
                suffixInflection('來ちまう', '來る', ['v5'], ['vk']),
            ],
        },
        '-しまう': {
            name: '-しまう',
            rules: [
                suffixInflection('てしまう', 'て', ['v5'], ['-て']),
                suffixInflection('でしまう', 'で', ['v5'], ['-て']),
            ],
        },
        '-なさい': {
            name: '-なさい',
            rules: [
                suffixInflection('なさい', 'る', ['-なさい'], ['v1']),
                suffixInflection('いなさい', 'う', ['-なさい'], ['v5']),
                suffixInflection('きなさい', 'く', ['-なさい'], ['v5']),
                suffixInflection('ぎなさい', 'ぐ', ['-なさい'], ['v5']),
                suffixInflection('しなさい', 'す', ['-なさい'], ['v5']),
                suffixInflection('ちなさい', 'つ', ['-なさい'], ['v5']),
                suffixInflection('になさい', 'ぬ', ['-なさい'], ['v5']),
                suffixInflection('びなさい', 'ぶ', ['-なさい'], ['v5']),
                suffixInflection('みなさい', 'む', ['-なさい'], ['v5']),
                suffixInflection('りなさい', 'る', ['-なさい'], ['v5']),
                suffixInflection('じなさい', 'ずる', ['-なさい'], ['vz']),
                suffixInflection('しなさい', 'する', ['-なさい'], ['vs']),
                suffixInflection('為なさい', '為る', ['-なさい'], ['vs']),
                suffixInflection('きなさい', 'くる', ['-なさい'], ['vk']),
                suffixInflection('来なさい', '来る', ['-なさい'], ['vk']),
                suffixInflection('來なさい', '來る', ['-なさい'], ['vk']),
            ],
        },
        '-そう': {
            name: '-そう',
            rules: [
                suffixInflection('そう', 'い', [], ['adj-i']),
                suffixInflection('そう', 'る', [], ['v1']),
                suffixInflection('いそう', 'う', [], ['v5']),
                suffixInflection('きそう', 'く', [], ['v5']),
                suffixInflection('ぎそう', 'ぐ', [], ['v5']),
                suffixInflection('しそう', 'す', [], ['v5']),
                suffixInflection('ちそう', 'つ', [], ['v5']),
                suffixInflection('にそう', 'ぬ', [], ['v5']),
                suffixInflection('びそう', 'ぶ', [], ['v5']),
                suffixInflection('みそう', 'む', [], ['v5']),
                suffixInflection('りそう', 'る', [], ['v5']),
                suffixInflection('じそう', 'ずる', [], ['vz']),
                suffixInflection('しそう', 'する', [], ['vs']),
                suffixInflection('為そう', '為る', [], ['vs']),
                suffixInflection('きそう', 'くる', [], ['vk']),
                suffixInflection('来そう', '来る', [], ['vk']),
                suffixInflection('來そう', '來る', [], ['vk']),
            ],
        },
        '-すぎる': {
            name: '-すぎる',
            rules: [
                suffixInflection('すぎる', 'い', ['v1'], ['adj-i']),
                suffixInflection('すぎる', 'る', ['v1'], ['v1']),
                suffixInflection('いすぎる', 'う', ['v1'], ['v5']),
                suffixInflection('きすぎる', 'く', ['v1'], ['v5']),
                suffixInflection('ぎすぎる', 'ぐ', ['v1'], ['v5']),
                suffixInflection('しすぎる', 'す', ['v1'], ['v5']),
                suffixInflection('ちすぎる', 'つ', ['v1'], ['v5']),
                suffixInflection('にすぎる', 'ぬ', ['v1'], ['v5']),
                suffixInflection('びすぎる', 'ぶ', ['v1'], ['v5']),
                suffixInflection('みすぎる', 'む', ['v1'], ['v5']),
                suffixInflection('りすぎる', 'る', ['v1'], ['v5']),
                suffixInflection('じすぎる', 'ずる', ['v1'], ['vz']),
                suffixInflection('しすぎる', 'する', ['v1'], ['vs']),
                suffixInflection('為すぎる', '為る', ['v1'], ['vs']),
                suffixInflection('きすぎる', 'くる', ['v1'], ['vk']),
                suffixInflection('来すぎる', '来る', ['v1'], ['vk']),
                suffixInflection('來すぎる', '來る', ['v1'], ['vk']),
            ],
        },
        '-過ぎる': {
            name: '-過ぎる',
            rules: [
                suffixInflection('過ぎる', 'い', ['v1'], ['adj-i']),
                suffixInflection('過ぎる', 'る', ['v1'], ['v1']),
                suffixInflection('い過ぎる', 'う', ['v1'], ['v5']),
                suffixInflection('き過ぎる', 'く', ['v1'], ['v5']),
                suffixInflection('ぎ過ぎる', 'ぐ', ['v1'], ['v5']),
                suffixInflection('し過ぎる', 'す', ['v1'], ['v5']),
                suffixInflection('ち過ぎる', 'つ', ['v1'], ['v5']),
                suffixInflection('に過ぎる', 'ぬ', ['v1'], ['v5']),
                suffixInflection('び過ぎる', 'ぶ', ['v1'], ['v5']),
                suffixInflection('み過ぎる', 'む', ['v1'], ['v5']),
                suffixInflection('り過ぎる', 'る', ['v1'], ['v5']),
                suffixInflection('じ過ぎる', 'ずる', ['v1'], ['vz']),
                suffixInflection('し過ぎる', 'する', ['v1'], ['vs']),
                suffixInflection('為過ぎる', '為る', ['v1'], ['vs']),
                suffixInflection('き過ぎる', 'くる', ['v1'], ['vk']),
                suffixInflection('来過ぎる', '来る', ['v1'], ['vk']),
                suffixInflection('來過ぎる', '來る', ['v1'], ['vk']),
            ],
        },
        '-たい': {
            name: '-たい',
            rules: [
                suffixInflection('たい', 'る', ['adj-i'], ['v1']),
                suffixInflection('いたい', 'う', ['adj-i'], ['v5']),
                suffixInflection('きたい', 'く', ['adj-i'], ['v5']),
                suffixInflection('ぎたい', 'ぐ', ['adj-i'], ['v5']),
                suffixInflection('したい', 'す', ['adj-i'], ['v5']),
                suffixInflection('ちたい', 'つ', ['adj-i'], ['v5']),
                suffixInflection('にたい', 'ぬ', ['adj-i'], ['v5']),
                suffixInflection('びたい', 'ぶ', ['adj-i'], ['v5']),
                suffixInflection('みたい', 'む', ['adj-i'], ['v5']),
                suffixInflection('りたい', 'る', ['adj-i'], ['v5']),
                suffixInflection('じたい', 'ずる', ['adj-i'], ['vz']),
                suffixInflection('したい', 'する', ['adj-i'], ['vs']),
                suffixInflection('為たい', '為る', ['adj-i'], ['vs']),
                suffixInflection('きたい', 'くる', ['adj-i'], ['vk']),
                suffixInflection('来たい', '来る', ['adj-i'], ['vk']),
                suffixInflection('來たい', '來る', ['adj-i'], ['vk']),
            ],
        },
        '-たら': {
            name: '-たら',
            rules: [
                suffixInflection('かったら', 'い', [], ['adj-i']),
                suffixInflection('たら', 'る', [], ['v1']),
                suffixInflection('いたら', 'く', [], ['v5']),
                suffixInflection('いだら', 'ぐ', [], ['v5']),
                suffixInflection('したら', 'す', [], ['v5']),
                suffixInflection('ったら', 'う', [], ['v5']),
                suffixInflection('ったら', 'つ', [], ['v5']),
                suffixInflection('ったら', 'る', [], ['v5']),
                suffixInflection('んだら', 'ぬ', [], ['v5']),
                suffixInflection('んだら', 'ぶ', [], ['v5']),
                suffixInflection('んだら', 'む', [], ['v5']),
                suffixInflection('じたら', 'ずる', [], ['vz']),
                suffixInflection('したら', 'する', [], ['vs']),
                suffixInflection('為たら', '為る', [], ['vs']),
                suffixInflection('きたら', 'くる', [], ['vk']),
                suffixInflection('来たら', '来る', [], ['vk']),
                suffixInflection('來たら', '來る', [], ['vk']),
                ...irregularVerbSuffixInflections('たら', [], ['v5']),
                suffixInflection('ましたら', 'ます', [], ['-ます']),
            ],
        },
        '-たり': {
            name: '-たり',
            rules: [
                suffixInflection('かったり', 'い', [], ['adj-i']),
                suffixInflection('たり', 'る', [], ['v1']),
                suffixInflection('いたり', 'く', [], ['v5']),
                suffixInflection('いだり', 'ぐ', [], ['v5']),
                suffixInflection('したり', 'す', [], ['v5']),
                suffixInflection('ったり', 'う', [], ['v5']),
                suffixInflection('ったり', 'つ', [], ['v5']),
                suffixInflection('ったり', 'る', [], ['v5']),
                suffixInflection('んだり', 'ぬ', [], ['v5']),
                suffixInflection('んだり', 'ぶ', [], ['v5']),
                suffixInflection('んだり', 'む', [], ['v5']),
                suffixInflection('じたり', 'ずる', [], ['vz']),
                suffixInflection('したり', 'する', [], ['vs']),
                suffixInflection('為たり', '為る', [], ['vs']),
                suffixInflection('きたり', 'くる', [], ['vk']),
                suffixInflection('来たり', '来る', [], ['vk']),
                suffixInflection('來たり', '來る', [], ['vk']),
                ...irregularVerbSuffixInflections('たり', [], ['v5']),
            ],
        },
        '-て': {
            name: '-て',
            rules: [
                suffixInflection('くて', 'い', ['-て'], ['adj-i']),
                suffixInflection('て', 'る', ['-て'], ['v1']),
                suffixInflection('いて', 'く', ['-て'], ['v5']),
                suffixInflection('いで', 'ぐ', ['-て'], ['v5']),
                suffixInflection('して', 'す', ['-て'], ['v5']),
                suffixInflection('って', 'う', ['-て'], ['v5']),
                suffixInflection('って', 'つ', ['-て'], ['v5']),
                suffixInflection('って', 'る', ['-て'], ['v5']),
                suffixInflection('んで', 'ぬ', ['-て'], ['v5']),
                suffixInflection('んで', 'ぶ', ['-て'], ['v5']),
                suffixInflection('んで', 'む', ['-て'], ['v5']),
                suffixInflection('じて', 'ずる', ['-て'], ['vz']),
                suffixInflection('して', 'する', ['-て'], ['vs']),
                suffixInflection('為て', '為る', ['-て'], ['vs']),
                suffixInflection('きて', 'くる', ['-て'], ['vk']),
                suffixInflection('来て', '来る', ['-て'], ['vk']),
                suffixInflection('來て', '來る', ['-て'], ['vk']),
                ...irregularVerbSuffixInflections('て', ['-て'], ['v5']),
                suffixInflection('まして', 'ます', [], ['-ます']),
            ],
        },
        '-ず': {
            name: '-ず',
            rules: [
                suffixInflection('ず', 'る', [], ['v1']),
                suffixInflection('かず', 'く', [], ['v5']),
                suffixInflection('がず', 'ぐ', [], ['v5']),
                suffixInflection('さず', 'す', [], ['v5']),
                suffixInflection('たず', 'つ', [], ['v5']),
                suffixInflection('なず', 'ぬ', [], ['v5']),
                suffixInflection('ばず', 'ぶ', [], ['v5']),
                suffixInflection('まず', 'む', [], ['v5']),
                suffixInflection('らず', 'る', [], ['v5']),
                suffixInflection('わず', 'う', [], ['v5']),
                suffixInflection('ぜず', 'ずる', [], ['vz']),
                suffixInflection('せず', 'する', [], ['vs']),
                suffixInflection('為ず', '為る', [], ['vs']),
                suffixInflection('こず', 'くる', [], ['vk']),
                suffixInflection('来ず', '来る', [], ['vk']),
                suffixInflection('來ず', '來る', [], ['vk']),
            ],
        },
        '-ぬ': {
            name: '-ぬ',
            rules: [
                suffixInflection('ぬ', 'る', [], ['v1']),
                suffixInflection('かぬ', 'く', [], ['v5']),
                suffixInflection('がぬ', 'ぐ', [], ['v5']),
                suffixInflection('さぬ', 'す', [], ['v5']),
                suffixInflection('たぬ', 'つ', [], ['v5']),
                suffixInflection('なぬ', 'ぬ', [], ['v5']),
                suffixInflection('ばぬ', 'ぶ', [], ['v5']),
                suffixInflection('まぬ', 'む', [], ['v5']),
                suffixInflection('らぬ', 'る', [], ['v5']),
                suffixInflection('わぬ', 'う', [], ['v5']),
                suffixInflection('ぜぬ', 'ずる', [], ['vz']),
                suffixInflection('せぬ', 'する', [], ['vs']),
                suffixInflection('為ぬ', '為る', [], ['vs']),
                suffixInflection('こぬ', 'くる', [], ['vk']),
                suffixInflection('来ぬ', '来る', [], ['vk']),
                suffixInflection('來ぬ', '來る', [], ['vk']),
            ],
        },
        '-ん': {
            name: '-ん',
            rules: [
                suffixInflection('ん', 'る', ['-ん'], ['v1']),
                suffixInflection('かん', 'く', ['-ん'], ['v5']),
                suffixInflection('がん', 'ぐ', ['-ん'], ['v5']),
                suffixInflection('さん', 'す', ['-ん'], ['v5']),
                suffixInflection('たん', 'つ', ['-ん'], ['v5']),
                suffixInflection('なん', 'ぬ', ['-ん'], ['v5']),
                suffixInflection('ばん', 'ぶ', ['-ん'], ['v5']),
                suffixInflection('まん', 'む', ['-ん'], ['v5']),
                suffixInflection('らん', 'る', ['-ん'], ['v5']),
                suffixInflection('わん', 'う', ['-ん'], ['v5']),
                suffixInflection('ぜん', 'ずる', ['-ん'], ['vz']),
                suffixInflection('せん', 'する', ['-ん'], ['vs']),
                suffixInflection('為ん', '為る', ['-ん'], ['vs']),
                suffixInflection('こん', 'くる', ['-ん'], ['vk']),
                suffixInflection('来ん', '来る', ['-ん'], ['vk']),
                suffixInflection('來ん', '來る', ['-ん'], ['vk']),
            ],
        },
        '-ざる': {
            name: '-ざる',
            rules: [
                suffixInflection('ざる', 'る', [], ['v1']),
                suffixInflection('かざる', 'く', [], ['v5']),
                suffixInflection('がざる', 'ぐ', [], ['v5']),
                suffixInflection('さざる', 'す', [], ['v5']),
                suffixInflection('たざる', 'つ', [], ['v5']),
                suffixInflection('なざる', 'ぬ', [], ['v5']),
                suffixInflection('ばざる', 'ぶ', [], ['v5']),
                suffixInflection('まざる', 'む', [], ['v5']),
                suffixInflection('らざる', 'る', [], ['v5']),
                suffixInflection('わざる', 'う', [], ['v5']),
                suffixInflection('ぜざる', 'ずる', [], ['vz']),
                suffixInflection('せざる', 'する', [], ['vs']),
                suffixInflection('為ざる', '為る', [], ['vs']),
                suffixInflection('こざる', 'くる', [], ['vk']),
                suffixInflection('来ざる', '来る', [], ['vk']),
                suffixInflection('來ざる', '來る', [], ['vk']),
            ],
        },
        '-く': {
            name: '-く',
            rules: [
                suffixInflection('く', 'い', ['-く'], ['adj-i']),
            ],
        },
        'causative': {
            name: 'causative',
            rules: [
                suffixInflection('させる', 'る', ['v1'], ['v1']),
                suffixInflection('かせる', 'く', ['v1'], ['v5']),
                suffixInflection('がせる', 'ぐ', ['v1'], ['v5']),
                suffixInflection('させる', 'す', ['v1'], ['v5']),
                suffixInflection('たせる', 'つ', ['v1'], ['v5']),
                suffixInflection('なせる', 'ぬ', ['v1'], ['v5']),
                suffixInflection('ばせる', 'ぶ', ['v1'], ['v5']),
                suffixInflection('ませる', 'む', ['v1'], ['v5']),
                suffixInflection('らせる', 'る', ['v1'], ['v5']),
                suffixInflection('わせる', 'う', ['v1'], ['v5']),
                suffixInflection('じさせる', 'ずる', ['v1'], ['vz']),
                suffixInflection('ぜさせる', 'ずる', ['v1'], ['vz']),
                suffixInflection('させる', 'する', ['v1'], ['vs']),
                suffixInflection('為せる', '為る', ['v1'], ['vs']),
                suffixInflection('せさせる', 'する', ['v1'], ['vs']),
                suffixInflection('為させる', '為る', ['v1'], ['vs']),
                suffixInflection('こさせる', 'くる', ['v1'], ['vk']),
                suffixInflection('来させる', '来る', ['v1'], ['vk']),
                suffixInflection('來させる', '來る', ['v1'], ['vk']),
            ],
        },
        'imperative': {
            name: 'imperative',
            rules: [
                suffixInflection('ろ', 'る', [], ['v1']),
                suffixInflection('よ', 'る', [], ['v1']),
                suffixInflection('え', 'う', [], ['v5']),
                suffixInflection('け', 'く', [], ['v5']),
                suffixInflection('げ', 'ぐ', [], ['v5']),
                suffixInflection('せ', 'す', [], ['v5']),
                suffixInflection('て', 'つ', [], ['v5']),
                suffixInflection('ね', 'ぬ', [], ['v5']),
                suffixInflection('べ', 'ぶ', [], ['v5']),
                suffixInflection('め', 'む', [], ['v5']),
                suffixInflection('れ', 'る', [], ['v5']),
                suffixInflection('じろ', 'ずる', [], ['vz']),
                suffixInflection('ぜよ', 'ずる', [], ['vz']),
                suffixInflection('しろ', 'する', [], ['vs']),
                suffixInflection('せよ', 'する', [], ['vs']),
                suffixInflection('為ろ', '為る', [], ['vs']),
                suffixInflection('為よ', '為る', [], ['vs']),
                suffixInflection('こい', 'くる', [], ['vk']),
                suffixInflection('来い', '来る', [], ['vk']),
                suffixInflection('來い', '來る', [], ['vk']),
            ],
        },
        'continuative': {
            name: 'continuative',
            rules: [
                suffixInflection('い', 'いる', [], ['v1d']),
                suffixInflection('え', 'える', [], ['v1d']),
                suffixInflection('き', 'きる', [], ['v1d']),
                suffixInflection('ぎ', 'ぎる', [], ['v1d']),
                suffixInflection('け', 'ける', [], ['v1d']),
                suffixInflection('げ', 'げる', [], ['v1d']),
                suffixInflection('じ', 'じる', [], ['v1d']),
                suffixInflection('せ', 'せる', [], ['v1d']),
                suffixInflection('ぜ', 'ぜる', [], ['v1d']),
                suffixInflection('ち', 'ちる', [], ['v1d']),
                suffixInflection('て', 'てる', [], ['v1d']),
                suffixInflection('で', 'でる', [], ['v1d']),
                suffixInflection('に', 'にる', [], ['v1d']),
                suffixInflection('ね', 'ねる', [], ['v1d']),
                suffixInflection('ひ', 'ひる', [], ['v1d']),
                suffixInflection('び', 'びる', [], ['v1d']),
                suffixInflection('へ', 'へる', [], ['v1d']),
                suffixInflection('べ', 'べる', [], ['v1d']),
                suffixInflection('み', 'みる', [], ['v1d']),
                suffixInflection('め', 'める', [], ['v1d']),
                suffixInflection('り', 'りる', [], ['v1d']),
                suffixInflection('れ', 'れる', [], ['v1d']),
                suffixInflection('い', 'う', [], ['v5']),
                suffixInflection('き', 'く', [], ['v5']),
                suffixInflection('ぎ', 'ぐ', [], ['v5']),
                suffixInflection('し', 'す', [], ['v5']),
                suffixInflection('ち', 'つ', [], ['v5']),
                suffixInflection('に', 'ぬ', [], ['v5']),
                suffixInflection('び', 'ぶ', [], ['v5']),
                suffixInflection('み', 'む', [], ['v5']),
                suffixInflection('り', 'る', [], ['v5']),
                suffixInflection('き', 'くる', [], ['vk']),
                suffixInflection('し', 'する', [], ['vs']),
                suffixInflection('来', '来る', [], ['vk']),
                suffixInflection('來', '來る', [], ['vk']),
            ],
        },
        'negative': {
            name: 'negative',
            rules: [
                suffixInflection('くない', 'い', ['adj-i'], ['adj-i']),
                suffixInflection('ない', 'る', ['adj-i'], ['v1']),
                suffixInflection('かない', 'く', ['adj-i'], ['v5']),
                suffixInflection('がない', 'ぐ', ['adj-i'], ['v5']),
                suffixInflection('さない', 'す', ['adj-i'], ['v5']),
                suffixInflection('たない', 'つ', ['adj-i'], ['v5']),
                suffixInflection('なない', 'ぬ', ['adj-i'], ['v5']),
                suffixInflection('ばない', 'ぶ', ['adj-i'], ['v5']),
                suffixInflection('まない', 'む', ['adj-i'], ['v5']),
                suffixInflection('らない', 'る', ['adj-i'], ['v5']),
                suffixInflection('わない', 'う', ['adj-i'], ['v5']),
                suffixInflection('じない', 'ずる', ['adj-i'], ['vz']),
                suffixInflection('しない', 'する', ['adj-i'], ['vs']),
                suffixInflection('為ない', '為る', ['adj-i'], ['vs']),
                suffixInflection('こない', 'くる', ['adj-i'], ['vk']),
                suffixInflection('来ない', '来る', ['adj-i'], ['vk']),
                suffixInflection('來ない', '來る', ['adj-i'], ['vk']),
                suffixInflection('ません', 'ます', ['-ません'], ['-ます']),
            ],
        },
        'passive': {
            name: 'passive',
            rules: [
                suffixInflection('かれる', 'く', ['v1'], ['v5']),
                suffixInflection('がれる', 'ぐ', ['v1'], ['v5']),
                suffixInflection('される', 'す', ['v1'], ['v5d', 'v5sp']),
                suffixInflection('たれる', 'つ', ['v1'], ['v5']),
                suffixInflection('なれる', 'ぬ', ['v1'], ['v5']),
                suffixInflection('ばれる', 'ぶ', ['v1'], ['v5']),
                suffixInflection('まれる', 'む', ['v1'], ['v5']),
                suffixInflection('われる', 'う', ['v1'], ['v5']),
                suffixInflection('られる', 'る', ['v1'], ['v5']),
                suffixInflection('じされる', 'ずる', ['v1'], ['vz']),
                suffixInflection('ぜされる', 'ずる', ['v1'], ['vz']),
                suffixInflection('される', 'する', ['v1'], ['vs']),
                suffixInflection('為れる', '為る', ['v1'], ['vs']),
                suffixInflection('こられる', 'くる', ['v1'], ['vk']),
                suffixInflection('来られる', '来る', ['v1'], ['vk']),
                suffixInflection('來られる', '來る', ['v1'], ['vk']),
            ],
        },
        '-た': {
            name: '-た',
            rules: [
                suffixInflection('かった', 'い', ['-た'], ['adj-i']),
                suffixInflection('た', 'る', ['-た'], ['v1']),
                suffixInflection('いた', 'く', ['-た'], ['v5']),
                suffixInflection('いだ', 'ぐ', ['-た'], ['v5']),
                suffixInflection('した', 'す', ['-た'], ['v5']),
                suffixInflection('った', 'う', ['-た'], ['v5']),
                suffixInflection('った', 'つ', ['-た'], ['v5']),
                suffixInflection('った', 'る', ['-た'], ['v5']),
                suffixInflection('んだ', 'ぬ', ['-た'], ['v5']),
                suffixInflection('んだ', 'ぶ', ['-た'], ['v5']),
                suffixInflection('んだ', 'む', ['-た'], ['v5']),
                suffixInflection('じた', 'ずる', ['-た'], ['vz']),
                suffixInflection('した', 'する', ['-た'], ['vs']),
                suffixInflection('為た', '為る', ['-た'], ['vs']),
                suffixInflection('きた', 'くる', ['-た'], ['vk']),
                suffixInflection('来た', '来る', ['-た'], ['vk']),
                suffixInflection('來た', '來る', ['-た'], ['vk']),
                ...irregularVerbSuffixInflections('た', ['-た'], ['v5']),
                suffixInflection('ました', 'ます', ['-た'], ['-ます']),
                suffixInflection('でした', '', ['-た'], ['-ません']),
                suffixInflection('かった', '', ['-た'], ['-ません', '-ん']),
            ],
        },
        '-ます': {
            name: '-ます',
            rules: [
                suffixInflection('ます', 'る', ['-ます'], ['v1']),
                suffixInflection('います', 'う', ['-ます'], ['v5d']),
                suffixInflection('きます', 'く', ['-ます'], ['v5d']),
                suffixInflection('ぎます', 'ぐ', ['-ます'], ['v5d']),
                suffixInflection('します', 'す', ['-ます'], ['v5d', 'v5s']),
                suffixInflection('ちます', 'つ', ['-ます'], ['v5d']),
                suffixInflection('にます', 'ぬ', ['-ます'], ['v5d']),
                suffixInflection('びます', 'ぶ', ['-ます'], ['v5d']),
                suffixInflection('みます', 'む', ['-ます'], ['v5d']),
                suffixInflection('ります', 'る', ['-ます'], ['v5d']),
                suffixInflection('じます', 'ずる', ['-ます'], ['vz']),
                suffixInflection('します', 'する', ['-ます'], ['vs']),
                suffixInflection('為ます', '為る', ['-ます'], ['vs']),
                suffixInflection('きます', 'くる', ['-ます'], ['vk']),
                suffixInflection('来ます', '来る', ['-ます'], ['vk']),
                suffixInflection('來ます', '來る', ['-ます'], ['vk']),
                suffixInflection('くあります', 'い', ['-ます'], ['adj-i']),
            ],
        },
        'potential': {
            name: 'potential',
            rules: [
                suffixInflection('れる', 'る', ['v1'], ['v1', 'v5d']),
                suffixInflection('える', 'う', ['v1'], ['v5d']),
                suffixInflection('ける', 'く', ['v1'], ['v5d']),
                suffixInflection('げる', 'ぐ', ['v1'], ['v5d']),
                suffixInflection('せる', 'す', ['v1'], ['v5d']),
                suffixInflection('てる', 'つ', ['v1'], ['v5d']),
                suffixInflection('ねる', 'ぬ', ['v1'], ['v5d']),
                suffixInflection('べる', 'ぶ', ['v1'], ['v5d']),
                suffixInflection('める', 'む', ['v1'], ['v5d']),
                suffixInflection('できる', 'する', ['v1'], ['vs']),
                suffixInflection('出来る', 'する', ['v1'], ['vs']),
                suffixInflection('これる', 'くる', ['v1'], ['vk']),
                suffixInflection('来れる', '来る', ['v1'], ['vk']),
                suffixInflection('來れる', '來る', ['v1'], ['vk']),
            ],
        },
        'potential or passive': {
            name: 'potential or passive',
            rules: [
                suffixInflection('られる', 'る', ['v1'], ['v1']),
                suffixInflection('ざれる', 'ずる', ['v1'], ['vz']),
                suffixInflection('ぜられる', 'ずる', ['v1'], ['vz']),
                suffixInflection('せられる', 'する', ['v1'], ['vs']),
                suffixInflection('為られる', '為る', ['v1'], ['vs']),
                suffixInflection('こられる', 'くる', ['v1'], ['vk']),
                suffixInflection('来られる', '来る', ['v1'], ['vk']),
                suffixInflection('來られる', '來る', ['v1'], ['vk']),
            ],
        },
        'volitional': {
            name: 'volitional',
            rules: [
                suffixInflection('よう', 'る', [], ['v1']),
                suffixInflection('おう', 'う', [], ['v5']),
                suffixInflection('こう', 'く', [], ['v5']),
                suffixInflection('ごう', 'ぐ', [], ['v5']),
                suffixInflection('そう', 'す', [], ['v5']),
                suffixInflection('とう', 'つ', [], ['v5']),
                suffixInflection('のう', 'ぬ', [], ['v5']),
                suffixInflection('ぼう', 'ぶ', [], ['v5']),
                suffixInflection('もう', 'む', [], ['v5']),
                suffixInflection('ろう', 'る', [], ['v5']),
                suffixInflection('じよう', 'ずる', [], ['vz']),
                suffixInflection('しよう', 'する', [], ['vs']),
                suffixInflection('為よう', '為る', [], ['vs']),
                suffixInflection('こよう', 'くる', [], ['vk']),
                suffixInflection('来よう', '来る', [], ['vk']),
                suffixInflection('來よう', '來る', [], ['vk']),
                suffixInflection('ましょう', 'ます', [], ['-ます']),
                suffixInflection('かろう', 'い', [], ['adj-i']),
            ],
        },
        '-mai': {
            name: '-mai',
            rules: [
                suffixInflection('まい', '', [], ['v']),
                suffixInflection('まい', 'る', [], ['v1']),
                suffixInflection('じまい', 'ずる', [], ['vz']),
                suffixInflection('しまい', 'する', [], ['vs']),
                suffixInflection('為まい', '為る', [], ['vs']),
                suffixInflection('こまい', 'くる', [], ['vk']),
                suffixInflection('来まい', '来る', [], ['vk']),
                suffixInflection('來まい', '來る', [], ['vk']),
                suffixInflection('まい', '', [], ['-ます']),
            ],
        },
    },
};
